# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('unidad', models.CharField(blank=True, max_length=4, null=True)),
                ('graficas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensores',
                'managed': False,
            },
        ),
    ]
